---
kind: pipeline
type: docker
name: pipeline

steps:
- name: publish flutter-base latest
  image: plugins/docker
  settings:
    repo: pingu/flutter
    tags: latest
    dockerfile: flutter-base/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]

- name: publish flutter-base tagged
  image: plugins/docker
  settings:
    repo: pingu/flutter
    tags: ${DRONE_TAG}
    dockerfile: flutter-base/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    event:
      - tag
